- platform: group
  name: Thermal Perimeter
  unique_id: thermal_perimeter
  entities:
    - binary_sensor.bathroom_1_window_1
    - binary_sensor.bathroom_1_window_2
    - binary_sensor.bedroom_1_window
    - binary_sensor.bedroom_2_window
    - binary_sensor.den_window
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.great_room_door
    - binary_sensor.great_room_window
    - binary_sensor.kitchen_window
    - binary_sensor.office_1_window
    - binary_sensor.office_2_window

- platform: trend
  sensors:
    indoor_garden_humidity_falling:
      # 1% drop in 10 minutes range.
      entity_id: sensor.indoor_garden_humidity
      friendly_name: Indoor Humidity Falling
      max_samples: 10
      min_gradient: -0.0016
      sample_duration: 600

    indoor_garden_humidity_rising:
      # 1% raise in 10 minutes range.
      entity_id: sensor.indoor_garden_humidity
      friendly_name: Indoor Humidity Rising
      max_samples: 10
      min_gradient: 0.0016
      sample_duration: 600

    indoor_garden_temperature_falling:
      # 1°F drop in 10 minutes range.
      entity_id: sensor.indoor_garden_temperature
      max_samples: 10
      min_gradient: -0.0016
      sample_duration: 600

    indoor_garden_temperature_rising:
      # 1°F raise in 10 minutes range.
      entity_id: sensor.indoor_garden_temperature
      max_samples: 12
      min_gradient: 0.0016
      sample_duration: 3600
