- platform: workday
  add_holidays:
    - 2021-04-02
    - 2022-04-15
    - 2023-04-07
  country: US
  name: US Work Day

- platform: workday
  country: US
  excludes: [sun, holiday]
  name: USPS Pickup Day
  workdays: [mon, tue, wed, thu, fri, sat]
