- platform: workday
  country: !secret country
  name: Work Day

- platform: workday
  country: !secret country
  excludes: [sun, holiday]
  name: Pickup Day
  province: !secret province
  workdays: [mon, tue, wed, thu, fri, sat]
